
### VISUALIZAR TODOS OS USER
GET http://localhost:3000/user
content-type: application/json
#Authorization: Bearer 


### CREATE USER
POST http://localhost:3000/user 
content-type: application/json

{
    "name": "marcep",
    "phone": "11993787458",
    "email": "marcep@gmail.com.br",
    "cpf" : "39518758794",
    "password": "marcep123"
}

### IDENTIFIY USER FOR ID

GET http://localhost:3000/user/2
content-type: application/json


### ATUALIZAR SENHA USER
PATCH http://localhost:3000/user 
content-type: application/json

{
    "newPassword": "marcep123",
    "lastPassword": "marcep123"
}

