### CRIAR DADOS DE JOGADORES
POST http://localhost:3085/api/v1/jogadores
content-type: application/json
Authorization: 

{
    "telefoneCelular": "11987541526" ,
    "email": "anderson@terra.com",
    "nome": "anderson silva"
}

### CRIAR DADOS DE JOGADORES RBMQTT
POST http://localhost:3085/api/v1/jogadores
content-type: application/json
Authorization: 

{
    "telefoneCelular": "11987541526" ,
    "email": "anderson@terra.com",
    "nome": "anderson silva"
}

### ATUALIZAR DADOS DE JOGADORES.
PUT http://localhost:3085/api/v1/jogadores/6957bbd1d00b9cdc7476d8cb
content-type: application/json
Authorization: 

{
    "telefoneCelular": "11999999777",
    "nome": "anderson silva"
}


### CHAMA JOGADORES
GET http://localhost:3085/api/v1/jogadores
content-type: application/json
Authorization: 


### CHAMA JOGADORES POR EMAIL
GET http://localhost:3085/api/v1/jogadores/69b1cf83cf5ad65ca5051b41
content-type: application/json
Authorization: 


### DELETAR JOGADOR 
DELETE  http://localhost:3085/api/v1/jogadores/694ac9aa7d22259c15067ef2
content-type: application/json
Authorization: 