### CRIAR DADOS DE JOGADORES
POST http://localhost:3085/api/v1/jogadores
content-type: application/json
Authorization: 

{
    "telefoneCelular": "11987541526" ,
    "email": "anderson@terra.com",
    "nome": "anderson silva"
}

### CRIAR DADOS DE JOGADORES RBMQTT
POST http://localhost:3085/api/v1/jogadores
content-type: application/json
Authorization: 

{
    "telefoneCelular": "11987541526" ,
    "email": "anderson@terra.com",
    "nome": "anderson silva"
}


### ATUALIZAR DADOS DE JOGADORES.
PUT http://localhost:3085/api/v1/jogadores/69b1cf83cf5ad65ca5051b41
content-type: application/json
Authorization: 

{
    "telefoneCelular": "11999999855",
    "nome": "lari Silva"
}


### CHAMA JOGADORES
GET http://localhost:3085/api/v1/jogadores
content-type: application/json
Authorization: 

### CONSULTAR POR CATEGORIA QUERY RABBITMQ 'id do jogador'
GET http://localhost:3085/api/v1/jogadores?idJogador=69f559bc816c79cfb8ec7202
content-type: application/json
Authorization: 

### CHAMA JOGADORES POR ID
GET http://localhost:3085/api/v1/jogadores/69b1cf83cf5ad65ca5051b41
content-type: application/json
Authorization: 


### DELETAR JOGADOR 
DELETE  http://localhost:3085/api/v1/jogadores/6a08e8c0165a24d51cce3786
content-type: application/json
Authorization: 

### UPLOAD DE ARQUIVO
POST http://localhost:3085/api/v1/jogadores
content-type: application/json
Authorization: 

{
    "telefoneCelular": "11987541526" ,
    "email": "anderson@terra.com",
    "nome": "anderson silva"
}